version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: race-track-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: RaceTrackDb
    ports:
      - "5432:5432"
    volumes:
      - race_track_data:/var/lib/postgresql/data

volumes:
  race_track_data: